language: ruby
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0

before_script:
  - cp test/database.yml.example test/database.yml
  - mysql -e 'CREATE DATABASE mass_insert_test;'
  - psql -c 'CREATE DATABASE mass_insert_test;' -U postgres
