language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"

before_script:
  - mysql -e 'create database mysql2_test;'
  - psql -c 'create database postgresql_test;' -U postgres
  - cd spec/dummy
  - rake db:migrate RAILS_ENV=mysql2
  - rake db:migrate RAILS_ENV=postgresql
  - rake db:migrate RAILS_ENV=sqlite3
  - cd ../..
